name: form_ejc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  lucid_validation: ^1.2.5
  provider: ^6.1.2
  result_dart: ^2.0.0
  image_picker: ^1.0.4
  shadcn_ui: ^0.22.5
  result_command: ^1.3.0
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
